#!/bin/sh

# Builds and watches the current directory
# Starts a web server at the _site directory

set -e
cd $(dirname "$0")/..
cd www

# We want to start the server from the _site directory
# where everything was built by the docker-site-builder script


echo $JUPYTERHUB_SERVICE_PREFIX

jupyter-notebook --port=8888 --ip="*" --no-browser --NotebookApp.token="" \
                 --NotebookApp.allow_remote_access=True \
                 --NotebookApp.allow_origin="*" # --NotebookApp.default_url="/files/Home.html"

# Don't exit

while true; do
  sleep 600
done
